
name: Skript

description: Customize Minecraft's mechanics with simple scripts written in plain English sentences.

author: Njol
website: http://njol.ch/projects/skript

main: ch.njol.skript.Skript

version: ${project.version}

commands:
    skript:
        description: Skript's main command. Type '/skript help' for more information.
        aliases: [sk]
        permission: skript.admin
        usage: /skript help

soft-depend: [SQLibrary, Vault, WorldGuard, Factions]

permissions:
    skript.*:
        default: false
        children:
            skript.effectcommands: true
            skript.admin: true
            #skript.config: true
    skript.effectcommands:
        default: false
        description: Allows to use effects as commands, e.g. '!set health to 10'
    skript.admin:
        default: op
        description: Allows to use administrative commands and to recieve notifications of new versions.
#    skript.config:
#        description: allows to modify the configuration files via commands
#        default: false
